from pathlib import Path

import pandas as pd
import streamlit as st

from src.etl.loader import load_core_datasets


# ---------------------------------------------------------
# Load all core datasets once
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def _get_datasets():
    return load_core_datasets()


# ---------------------------------------------------------
# Company data
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_companies():
    datasets = _get_datasets()
    return datasets["companies"].copy()


# ---------------------------------------------------------
# Financial ratios
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_ratios(ticker, year=None):
    datasets = _get_datasets()

    ratios = datasets["financial_ratios"].copy()

    ratios = ratios[
        ratios["company_id"].astype(str) == str(ticker)
    ].copy()

    # Remove duplicate company-year records
    ratios = ratios.drop_duplicates(
        subset=["company_id", "year"],
        keep="first"
    )

    if year is not None:
        year_str = str(year)

        ratios = ratios[
            ratios["year"].astype(str).str.endswith(year_str)
        ].copy()

    return ratios


# ---------------------------------------------------------
# Profit & Loss
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_pl(ticker):
    datasets = _get_datasets()

    df = datasets["profitandloss"].copy()

    return df[
        df["company_id"].astype(str) == str(ticker)
    ].copy()


# ---------------------------------------------------------
# Balance Sheet
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_bs(ticker):
    datasets = _get_datasets()

    df = datasets["balancesheet"].copy()

    return df[
        df["company_id"].astype(str) == str(ticker)
    ].copy()


# ---------------------------------------------------------
# Cash Flow
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_cf(ticker):
    datasets = _get_datasets()

    df = datasets["cashflow"].copy()

    return df[
        df["company_id"].astype(str) == str(ticker)
    ].copy()


# ---------------------------------------------------------
# Sectors
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_sectors():
    datasets = _get_datasets()

    return datasets["sectors"].copy()


# ---------------------------------------------------------
# Peer Groups
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_peers(group_name):
    datasets = _get_datasets()

    df = datasets["peer_groups"].copy()

    possible_columns = [
        "group_name",
        "peer_group",
        "group",
    ]

    group_column = next(
        (
            column
            for column in possible_columns
            if column in df.columns
        ),
        None,
    )

    if group_column is None:
        return pd.DataFrame()

    return df[
        df[group_column].astype(str) == str(group_name)
    ].copy()


# ---------------------------------------------------------
# Valuation
# ---------------------------------------------------------

@st.cache_data(ttl=600)
def get_valuation(ticker):
    """
    Load valuation summary generated by the valuation module.
    """

    path = Path("output/valuation_summary.xlsx")

    if not path.exists():
        return pd.DataFrame()

    df = pd.read_excel(path)

    return df[
        df["company_id"].astype(str) == str(ticker)
    ].copy()